# Generated by Django 3.2.9 on 2021-11-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='promise.candidates')),
            ],
        ),
    ]
