# Generated by Django 3.2.9 on 2021-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('realm', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=100)),
            ],
        ),
    ]
