# Generated by Django 3.2.9 on 2021-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promises',
            name='contents',
            field=models.TextField(),
        ),
    ]
