# Generated by Django 3.2.9 on 2021-11-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='id',
            new_name='hubo_id',
        ),
    ]
